name = "uploud-api"
main = "worker.js"
compatibility_date = "2024-03-20"

# Przypinamy Twój dysk (Bucket) z Cloudflare
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "przecho" 

# Zmienne środowiskowe, które Cloudflare musi znać
[vars]
ACCOUNT_ID = "88c5c67633b72a26b0bff11805e73fb4"
BUCKET_NAME = "przecho"
